server:
  port: 8005

spring:
  application:
    name: ANALYTICS-REPORTING-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8006/eureka/